feat: псевдофикс хопперов
При работе мода возникала проблема:
[main/ERROR] [com.lothrazar.cyclic.ModCyclic/]: An unknown has broken the vanilla hopper, causing compatibility issues
java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{cyclic:hopper_fluid}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?]
	at net.minecraft.block.HopperBlock.handler$zfn000$hplus$getOutlineShape(SourceFile:562) ~[?:?]
	at net.minecraft.block.HopperBlock.func_220053_a(SourceFile) ~[?:?]
	at com.lothrazar.cyclic.block.hopper.BlockSimpleHopper.getShapeHopper(BlockSimpleHopper.java:77) ~[cyclic:1.16.5-1.6.1]

Пока-что я сделал псевдофикс шейпхоппера, далее уже исправлю саму логику хоппера.